const { borderColor } = require("@mui/system");

module.exports = {
  appName: "Monarcle",
  iconAlt: "Icon of a knight charging into battle",
  placeholderText: "Monarch",
  variant: "number",
  theme: {
    background: "#181617",
    secondary: "#252525",
    text: "white",
    fontFamily: "UnifrakturMaguntia",
  },
  data: [
    {
      name: "Henry IV",
      gender: "m",
      src: "Henry-IV.jpg",
      reignStarted: "1399",
    },
    {
      name: "Mary I",
      gender: "f",
      src: "Mary-I.jpg",
      reignStarted: "1553",
    },
    {
      name: "Richard III",
      gender: "m",
      src: "Richard-III.jpg",
      reignStarted: "1483",
    },
    {
      name: "Henry II",
      gender: "m",
      src: "Henry-II.jpg",
      reignStarted: "1154",
    },
    {
      name: "William II",
      gender: "m",
      src: "William-II.jpg",
      reignStarted: "1087",
    },
    {
      name: "Richard I",
      gender: "m",
      src: "Richard-I.jpg",
      reignStarted: "1189",
      hints: [
        "He earned the nickname 'Lionheart' due to his reputation as a brave and skilled military leader, particularly during the Third Crusade.",
        "Despite ruling for nearly ten years, he spent very little time in England, preferring to campaign in France and the Holy Land.",
        "He negotiated a truce with Saladin in 1192, allowing Christian pilgrims access to Jerusalem despite failing to capture the city.",
        "He was captured and held for ransom by the Holy Roman Emperor on his way back from the Crusades, with England paying an enormous sum for his release.",
        "He died in 1199 from an infected wound sustained during a siege in France, leaving no legitimate heir, which led to a succession crisis.",
      ],
    },
    {
      name: "Henry VIII",
      gender: "m",
      src: "Henry-VIII.jpg",
      reignStarted: "1509",
      hints: [
        "He is famous for having six wives, two of whom were executed, and his marriages played a significant role in shaping the country's religious and political landscape.",
        "His break from the Catholic Church led to the creation of the Church of England, after the Pope refused to annul his first marriage.",
        "He was a skilled musician and composer, credited with writing songs such as 'Pastime with Good Company.'",
        "His reign saw the dissolution of monasteries, leading to the redistribution of church lands and wealth to the crown and nobility.",
        "In later life, he became severely obese and suffered from health issues, likely worsened by a leg injury from a jousting accident.",
      ],
    },
    {
      name: "Henry III",
      gender: "m",
      src: "Henry-III.jpg",
      reignStarted: "1216",
      hints: [
        "He became king at the age of nine after his father’s death, leading to a long reign that lasted over 56 years, one of the longest in English history.",
        "He was deeply devoted to the Catholic Church and played a key role in the expansion of Westminster Abbey, where he is buried.",
        "His reign was marked by conflicts with the barons, leading to the Provisions of Oxford in 1258, which sought to limit royal power and establish a council to oversee governance.",
        "He faced a major rebellion led by Simon de Montfort, which resulted in the first English Parliament that included commoners.",
        "After years of civil unrest, his forces, led by his son, defeated the rebels, restoring royal authority and paving the way for future constitutional developments.",
      ],
    },
    {
      name: "Henry I",
      gender: "m",
      src: "Henry-I.jpg",
      reignStarted: "1100",
      hints: [
        "He was the fourth son of his predecessor and unexpectedly became king in 1100 after seizing the throne following his brother’s death.",
        "His reign was marked by administrative reforms, including improvements to the royal treasury and the introduction of the Exchequer system.",
        "He strengthened royal authority by issuing the Charter of Liberties, which outlined the rights of the barons and influenced later constitutional developments.",
        "His only legitimate son died in the White Ship disaster of 1120, leading to a succession crisis that eventually resulted in a civil war known as 'The Anarchy.'",
        "He was known for his intelligence and earned the nickname 'Beauclerc' due to his education and ability to govern effectively.",
      ],
    },
    {
      name: "Edward VI",
      gender: "m",
      src: "Edward-VI.jpg",
      reignStarted: "1547",
      hints: [
        "He became king at the age of nine, making him one of the youngest monarchs in English history, and his reign was dominated by regents who ruled on his behalf.",
        "His rule saw the advancement of Protestant reforms, including the introduction of the Book of Common Prayer, which shaped the future of the Church of England.",
        "He was highly educated and had a strong interest in religious and governmental affairs despite his young age.",
        "His health was fragile, and he died at just 15, leading to a succession crisis that briefly placed his cousin on the throne before his half-sister took power.",
        "His reign was marked by economic struggles, social unrest, and military challenges, including the suppression of rebellions in England and Scotland.",
      ],
    },
    {
      name: "John",
      gender: "m",
      src: "John.jpg",
      reignStarted: "1199",
      hints: [
        "They ruled England from 1199 to 1216 and were the youngest son of Henry II and Eleanor of Aquitaine.",
        "They lost most of England’s territories in France, including Normandy, after their military defeat to King Philip II of France.",
        "They are infamous for signing the Magna Carta in 1215, a document that limited the power of the monarchy and laid the foundation for constitutional government.",
        "They were excommunicated by Pope Innocent III in 1209 due to a dispute over the appointment of the Archbishop of Canterbury.",
        "Their reign was marked by heavy taxation and conflicts with his barons, leading to the First Barons' War (1215-1217).",
      ],
    },
    {
      name: "Jane",
      gender: "f",
      src: "Jane.jpg",
      reignStarted: "1553",
      hints: [
        "She was declared monarch of England in 1553 but reigned for only nine days before being deposed, making her the shortest-reigning English monarch in history.",
        "Her claim to the throne was orchestrated by powerful nobles who sought to prevent the return of Catholic rule under Mary Tudor.",
        "She was highly educated and known for her intelligence, with a strong grasp of classical languages and Protestant theology.",
        "After being removed from power, she was imprisoned in the Tower of London and initially spared, but later executed on orders from the new ruler.",
        "She was only around 16 or 17 years old at the time of her execution, making her one of the youngest monarchs to be sentenced to death in England.",
      ],
    },
    {
      name: "Stephen",
      gender: "m",
      src: "Stephen.jpg",
      reignStarted: "1135",
      hints: [
        "He seized the English throne in 1135, despite a prior agreement that the crown would pass to his cousin, leading to a prolonged civil war known as 'The Anarchy.'",
        "His reign was marked by a bitter struggle against the forces of Empress Matilda, who sought to reclaim the throne as the rightful heir.",
        "He was known for his generosity and chivalry, but his inability to maintain firm control over the barons led to widespread lawlessness.",
        "After years of conflict, he reached an agreement that recognized his rival’s son as his successor, effectively ending the civil war.",
        "His death in 1154 brought an end to a turbulent period in English history, paving the way for the rise of the Plantagenet dynasty.",
      ],
    },
    {
      name: "Edward I",
      gender: "m",
      src: "Edward-I.jpg",
      reignStarted: "1272",
      hints: [
        "He was known for his military campaigns, particularly his conquest of Wales, where he built a series of castles to secure English rule.",
        "He expelled the Jewish population from England in 1290, issuing the Edict of Expulsion, which remained in effect for over 350 years.",
        "His conflicts with Scotland led to wars against famous figures such as William Wallace and Robert the Bruce, earning him the nickname 'Hammer of the Scots.'",
        "He played a key role in the development of the English Parliament, summoning representatives from towns and counties to participate in governance.",
        "He was a physically imposing figure and an accomplished warrior, known for his strict sense of justice and legal reforms that helped shape English common law.",
      ],
    },
    {
      name: "Edward III",
      gender: "m",
      src: "Edward-III.jpg",
      reignStarted: "1327",
      hints: [
        "His reign saw the start of the Hundred Years' War, during which he claimed the French throne and won significant victories, including the Battle of Crécy.",
        "He established the Order of the Garter, one of the most prestigious chivalric orders in England, which still exists today.",
        "The Black Death struck England during his reign, killing a large portion of the population and leading to major social and economic changes.",
        "He had a long reign of 50 years, during which he strengthened the monarchy and oversaw the rise of the English longbow as a dominant weapon in warfare.",
        "His later years were marked by political instability and conflict among his sons, which contributed to the Wars of the Roses after his death.",
      ],
    },
    {
      name: "Philip",
      gender: "m",
      src: "Philip.jpg",
      reignStarted: "1554",
      hints: [
        "He became king at the age of seven and ruled for nearly 48 years, making his reign one of the longest in medieval French history.",
        "His early years were dominated by his mother, who acted as regent until he was old enough to govern independently.",
        "He faced conflicts with the papacy after marrying the wife of another noble, leading to his excommunication from the Church.",
        "His rule saw the gradual strengthening of royal authority, but much of his reign was marked by struggles against ambitious nobles and external threats.",
        "Despite his long rule, his reign was overshadowed by the rising power of the neighboring kingdom to the west, which later became a dominant force in medieval Europe.",
      ],
    },
    {
      name: "Edward II",
      gender: "m",
      src: "Edward-II.jpg",
      reignStarted: "1307",
      hints: [
        "He had a troubled reign marked by conflicts with his barons, largely due to his close relationships with certain favorites, which led to political unrest.",
        "He suffered a major military defeat at the Battle of Bannockburn in 1314, which secured the independence of Scotland from English rule.",
        "His reliance on unpopular advisors, including Piers Gaveston and later Hugh Despenser, led to rebellions and eventually his deposition.",
        "He was the first English monarch to be forcibly removed from the throne, as his own wife and her ally led a coup against him.",
        "He was imprisoned after being deposed, and his mysterious death soon afterward has led to centuries of speculation about its circumstances.",
      ],
    },
    {
      name: "Edward IV",
      gender: "m",
      src: "Edward-IV.jpg",
      reignStarted: "1461",
      hints: [
        "He was a key figure in the Wars of the Roses, leading the Yorkist faction to victory and claiming the throne twice during his lifetime.",
        "His marriage to a commoner caused tensions among his allies, as it disrupted political alliances and angered powerful nobles.",
        "He was known for his military prowess, winning decisive battles such as Towton and Barnet, which secured his reign.",
        "During his rule, he strengthened the monarchy by improving royal finances and promoting trade, helping to stabilize the economy.",
        "His unexpected death in 1483 led to a succession crisis, ultimately resulting in the rise of his younger brother as protector and the disappearance of his two sons, known as the Princes in the Tower.",
      ],
    },
    {
      name: "Edward V",
      gender: "m",
      src: "Edward-V.jpg",
      reignStarted: "1483",
    },
    {
      name: "Richard II",
      gender: "m",
      src: "Richard-II.jpg",
      reignStarted: "1377",
    },
    {
      name: "Henry VI",
      gender: "m",
      src: "Henry-VI.jpg",
      reignStarted: "1461",
      hints: [
        "He became King of England in 1422 at just nine months old, making him the youngest person ever to inherit the English throne.",
        "His reign saw the loss of nearly all English territories in France, including Normandy, during the latter stages of the Hundred Years' War.",
        "He was known for his piety and founded Eton College and King’s College, Cambridge, which remain prestigious institutions today.",
        "His mental instability led to periods of incapacity, during which Richard, Duke of York, was appointed Protector of the Realm.",
        "His rule was marked by the Wars of the Roses, a series of conflicts between the rival houses of Lancaster and York, ultimately leading to his deposition and eventual death in the Tower of London.",
      ],
    },
    {
      name: "Henry V",
      gender: "m",
      src: "Henry-V.jpeg",
      reignStarted: "1413",
    },
    {
      name: "Elizabeth I",
      gender: "f",
      src: "Elizabeth-I.jpg",
      reignStarted: "1558",
    },
    {
      name: "Henry VII",
      gender: "m",
      src: "Henry-VII.jpg",
      reignStarted: "1485",
    },
    {
      name: "William I",
      gender: "m",
      src: "William-I.jpg",
      reignStarted: "1066",
    },
  ],
};
