module.exports = {
  appName: "Monarcle",
  iconAlt: "Icon of a knight charging into battle",
  placeholderText: "Monarch",
  variant: "number",
  theme: {
    background: "#181617",
    secondary: "#282828",
    text: "white",
    fontFamily: "UnifrakturMaguntia",
    correct: "linear-gradient(90deg, #9ebd13 0%, #008552 100%)",
    incorrect:
      "linear-gradient(90deg,rgba(180, 58, 131, 1) 0%, rgba(253, 29, 29, 1) 100%)",
  },
  data: [
    {
      name: "Henry IV",
      gender: "m",
      src: "Henry-IV.jpg",
      reignStarted: "1399",
      hints: [
        "He became king of England as an infant, inheriting the throne at just nine months old, and later also became king of France during the Hundred Years’ War.",
        "His reign was plagued by periods of mental illness, during which he was unable to govern, leading to political instability and the rise of rival factions.",
        "He was a deeply pious and gentle ruler, more interested in religion and education than warfare or politics, and he founded institutions such as Eton College and King’s College, Cambridge.",
        "His inability to maintain order or assert strong leadership contributed to the outbreak of the Wars of the Roses between the houses of Lancaster and York.",
        "He was eventually deposed, briefly restored, and then imprisoned, where he died under mysterious circumstances, likely murdered in the Tower of London.",
      ],
    },
    {
      name: "Mary I",
      gender: "f",
      src: "Mary-I.jpg",
      reignStarted: "1553",
      hints: [
        "She was the first woman to rule England in her own right, ascending the throne after the brief reign of her cousin.",
        "Her attempts to restore Catholicism included the persecution of Protestants, leading to hundreds of executions and earning her a lasting nickname.",
        "She married a powerful European prince, hoping to secure a Catholic alliance, but the union was unpopular and produced no heir.",
        "Her reign was marked by economic difficulties, crop failures, and a series of rebellions, including one led by a former suitor.",
        "Despite her unpopularity at the time of her death, her efforts paved the way for the religious and political transformations that followed under her successor.",
      ],
    },
    {
      name: "Richard III",
      gender: "m",
      src: "Richard-III.jpg",
      reignStarted: "1483",
      hints: [
        "He came to power after declaring his nephews illegitimate, and their subsequent disappearance led to one of the most enduring mysteries in English history.",
        "His reign lasted just over two years and ended with his death in battle, making him the last English king to die on the battlefield.",
        "He was defeated by a rival claimant who established a new royal dynasty, marking the end of the Wars of the Roses.",
        "His reputation was heavily shaped by later propaganda and literary portrayals, particularly a famous play that depicted him as a villainous hunchback.",
        "In the 21st century, his remains were discovered beneath a car park in Leicester, confirming historical records about his burial location.",
      ],
    },
    {
      name: "Henry II",
      gender: "m",
      src: "Henry-II.jpg",
      reignStarted: "1154",
      hints: [
        "He was the first ruler of the Angevin Empire, controlling vast territories that stretched from Scotland to the Pyrenees.",
        "He implemented significant legal reforms, laying the groundwork for the English common law system and strengthening royal justice.",
        "His turbulent relationship with a high-ranking church official led to that man's infamous murder inside a cathedral, shocking Christendom.",
        "He had a famously stormy family life, with his wife and sons rebelling against him multiple times during his reign.",
        "His efforts to centralize power often put him at odds with both the nobility and the Church, shaping the nature of medieval monarchy.",
      ],
    },
    {
      name: "William II",
      gender: "m",
      src: "William-II.jpg",
      reignStarted: "1087",
      hints: [
        "He was the third son of his predecessor and inherited the English throne while his elder brother took control of Normandy.",
        "His reign was marked by frequent conflicts with the Church, especially over the appointment of bishops and the influence of the clergy.",
        "He was known for his harsh rule and heavy taxation, which made him unpopular among both nobles and commoners.",
        "He died suddenly while hunting in the New Forest under mysterious circumstances, leading to speculation that his death was not accidental.",
        "His unexpected death allowed his younger brother to quickly seize the throne, altering the line of succession.",
      ],
    },
    {
      name: "Richard I",
      gender: "m",
      src: "Richard-I.jpg",
      reignStarted: "1189",
      hints: [
        "He earned the nickname 'Lionheart' due to his reputation as a brave and skilled military leader, particularly during the Third Crusade.",
        "Despite ruling for nearly ten years, he spent very little time in England, preferring to campaign in France and the Holy Land.",
        "He negotiated a truce with Saladin in 1192, allowing Christian pilgrims access to Jerusalem despite failing to capture the city.",
        "He was captured and held for ransom by the Holy Roman Emperor on his way back from the Crusades, with England paying an enormous sum for his release.",
        "He died in 1199 from an infected wound sustained during a siege in France, leaving no legitimate heir, which led to a succession crisis.",
      ],
    },
    {
      name: "Henry VIII",
      gender: "m",
      src: "Henry-VIII.jpg",
      reignStarted: "1509",
      hints: [
        "He is famous for having six wives, two of whom were executed, and his marriages played a significant role in shaping the country's religious and political landscape.",
        "His break from the Catholic Church led to the creation of the Church of England, after the Pope refused to annul his first marriage.",
        "He was a skilled musician and composer, credited with writing songs such as 'Pastime with Good Company.'",
        "His reign saw the dissolution of monasteries, leading to the redistribution of church lands and wealth to the crown and nobility.",
        "In later life, he became severely obese and suffered from health issues, likely worsened by a leg injury from a jousting accident.",
      ],
    },
    {
      name: "Henry III",
      gender: "m",
      src: "Henry-III.jpg",
      reignStarted: "1216",
      hints: [
        "He became king at the age of nine after his father’s death, leading to a long reign that lasted over 56 years, one of the longest in English history.",
        "He was deeply devoted to the Catholic Church and played a key role in the expansion of Westminster Abbey, where he is buried.",
        "His reign was marked by conflicts with the barons, leading to the Provisions of Oxford in 1258, which sought to limit royal power and establish a council to oversee governance.",
        "He faced a major rebellion led by Simon de Montfort, which resulted in the first English Parliament that included commoners.",
        "After years of civil unrest, his forces, led by his son, defeated the rebels, restoring royal authority and paving the way for future constitutional developments.",
      ],
    },
    {
      name: "Henry I",
      gender: "m",
      src: "Henry-I.jpg",
      reignStarted: "1100",
      hints: [
        "He was the fourth son of his predecessor and unexpectedly became king in 1100 after seizing the throne following his brother’s death.",
        "His reign was marked by administrative reforms, including improvements to the royal treasury and the introduction of the Exchequer system.",
        "He strengthened royal authority by issuing the Charter of Liberties, which outlined the rights of the barons and influenced later constitutional developments.",
        "His only legitimate son died in the White Ship disaster of 1120, leading to a succession crisis that eventually resulted in a civil war known as 'The Anarchy.'",
        "He was known for his intelligence and earned the nickname 'Beauclerc' due to his education and ability to govern effectively.",
      ],
    },
    {
      name: "Edward VI",
      gender: "m",
      src: "Edward-VI.jpg",
      reignStarted: "1547",
      hints: [
        "He became king at the age of nine, making him one of the youngest monarchs in English history, and his reign was dominated by regents who ruled on his behalf.",
        "His rule saw the advancement of Protestant reforms, including the introduction of the Book of Common Prayer, which shaped the future of the Church of England.",
        "He was highly educated and had a strong interest in religious and governmental affairs despite his young age.",
        "His health was fragile, and he died at just 15, leading to a succession crisis that briefly placed his cousin on the throne before his half-sister took power.",
        "His reign was marked by economic struggles, social unrest, and military challenges, including the suppression of rebellions in England and Scotland.",
      ],
    },
    {
      name: "John",
      gender: "m",
      src: "John.jpg",
      reignStarted: "1199",
      hints: [
        "They ruled England from 1199 to 1216 and were the youngest son of Henry II and Eleanor of Aquitaine.",
        "They lost most of England’s territories in France, including Normandy, after their military defeat to King Philip II of France.",
        "They are infamous for signing the Magna Carta in 1215, a document that limited the power of the monarchy and laid the foundation for constitutional government.",
        "They were excommunicated by Pope Innocent III in 1209 due to a dispute over the appointment of the Archbishop of Canterbury.",
        "Their reign was marked by heavy taxation and conflicts with his barons, leading to the First Barons' War (1215-1217).",
      ],
    },
    {
      name: "Lady Jane Gray",
      gender: "f",
      src: "Jane.jpg",
      reignStarted: "1553",
      hints: [
        "She was declared monarch of England in 1553 but reigned for only nine days before being deposed, making her the shortest-reigning English monarch in history.",
        "Her claim to the throne was orchestrated by powerful nobles who sought to prevent the return of Catholic rule under Mary Tudor.",
        "She was highly educated and known for her intelligence, with a strong grasp of classical languages and Protestant theology.",
        "After being removed from power, she was imprisoned in the Tower of London and initially spared, but later executed on orders from the new ruler.",
        "She was only around 16 or 17 years old at the time of her execution, making her one of the youngest monarchs to be sentenced to death in England.",
      ],
    },
    {
      name: "Stephen",
      gender: "m",
      src: "Stephen.jpg",
      reignStarted: "1135",
      hints: [
        "He seized the English throne in 1135, despite a prior agreement that the crown would pass to his cousin, leading to a prolonged civil war known as 'The Anarchy.'",
        "His reign was marked by a bitter struggle against the forces of Empress Matilda, who sought to reclaim the throne as the rightful heir.",
        "He was known for his generosity and chivalry, but his inability to maintain firm control over the barons led to widespread lawlessness.",
        "After years of conflict, he reached an agreement that recognized his rival’s son as his successor, effectively ending the civil war.",
        "His death in 1154 brought an end to a turbulent period in English history, paving the way for the rise of the Plantagenet dynasty.",
      ],
    },
    {
      name: "Edward I",
      gender: "m",
      src: "Edward-I.jpg",
      reignStarted: "1272",
      hints: [
        "He was known for his military campaigns, particularly his conquest of Wales, where he built a series of castles to secure English rule.",
        "He expelled the Jewish population from England in 1290, issuing the Edict of Expulsion, which remained in effect for over 350 years.",
        "His conflicts with Scotland led to wars against famous figures such as William Wallace and Robert the Bruce, earning him the nickname 'Hammer of the Scots.'",
        "He played a key role in the development of the English Parliament, summoning representatives from towns and counties to participate in governance.",
        "He was a physically imposing figure and an accomplished warrior, known for his strict sense of justice and legal reforms that helped shape English common law.",
      ],
    },
    {
      name: "Edward III",
      gender: "m",
      src: "Edward-III.jpg",
      reignStarted: "1327",
      hints: [
        "His reign saw the start of the Hundred Years' War, during which he claimed the French throne and won significant victories, including the Battle of Crécy.",
        "He established the Order of the Garter, one of the most prestigious chivalric orders in England, which still exists today.",
        "The Black Death struck England during his reign, killing a large portion of the population and leading to major social and economic changes.",
        "He had a long reign of 50 years, during which he strengthened the monarchy and oversaw the rise of the English longbow as a dominant weapon in warfare.",
        "His later years were marked by political instability and conflict among his sons, which contributed to the Wars of the Roses after his death.",
      ],
    },
    {
      name: "Edward II",
      gender: "m",
      src: "Edward-II.jpg",
      reignStarted: "1307",
      hints: [
        "He had a troubled reign marked by conflicts with his barons, largely due to his close relationships with certain favorites, which led to political unrest.",
        "He suffered a major military defeat at the Battle of Bannockburn in 1314, which secured the independence of Scotland from English rule.",
        "His reliance on unpopular advisors, including Piers Gaveston and later Hugh Despenser, led to rebellions and eventually his deposition.",
        "He was the first English monarch to be forcibly removed from the throne, as his own wife and her ally led a coup against him.",
        "He was imprisoned after being deposed, and his mysterious death soon afterward has led to centuries of speculation about its circumstances.",
      ],
    },
    {
      name: "Edward IV",
      gender: "m",
      src: "Edward-IV.jpg",
      reignStarted: "1461",
      hints: [
        "He was a key figure in the Wars of the Roses, leading the Yorkist faction to victory and claiming the throne twice during his lifetime.",
        "His marriage to a commoner caused tensions among his allies, as it disrupted political alliances and angered powerful nobles.",
        "He was known for his military prowess, winning decisive battles such as Towton and Barnet, which secured his reign.",
        "During his rule, he strengthened the monarchy by improving royal finances and promoting trade, helping to stabilize the economy.",
        "His unexpected death in 1483 led to a succession crisis, ultimately resulting in the rise of his younger brother as protector and the disappearance of his two sons, known as the Princes in the Tower.",
      ],
    },
    {
      name: "Edward V",
      gender: "m",
      src: "Edward-V.jpg",
      reignStarted: "1483",
      hints: [
        "He became king as a child but was never crowned, and his brief reign lasted only a few months before he was declared illegitimate.",
        "He and his younger brother were placed in the Tower of London for their 'protection' and subsequently disappeared, leading to centuries of speculation.",
        "His reign marked a pivotal moment in the Wars of the Roses, as control shifted from the House of York to a new ruler.",
        "He was the eldest son of a powerful monarch and was expected to continue a strong dynasty before political upheaval intervened.",
        "His mysterious fate, along with that of his brother, gave rise to the legend of the Princes in the Tower and remains one of England’s most famous historical mysteries.",
      ],
    },
    {
      name: "Richard II",
      gender: "m",
      src: "Richard-II.jpg",
      reignStarted: "1377",
      hints: [
        "He became king at a young age and faced a major uprising early in his reign, which he initially calmed with a bold personal confrontation.",
        "His later rule was marked by increasing authoritarianism, including the punishment and exile of powerful nobles who opposed him.",
        "He was a patron of the arts and literature, supporting figures like Geoffrey Chaucer and promoting the use of English in official records.",
        "His attempts to consolidate power alienated many of the nobility, ultimately leading to his forced abdication by a rival claimant.",
        "He died in captivity under suspicious circumstances after being deposed, and his fall marked a turning point leading to decades of dynastic conflict.",
      ],
    },
    {
      name: "Henry VI",
      gender: "m",
      src: "Henry-VI.jpg",
      reignStarted: "1461",
      hints: [
        "He became King of England in 1422 at just nine months old, making him the youngest person ever to inherit the English throne.",
        "His reign saw the loss of nearly all English territories in France, including Normandy, during the latter stages of the Hundred Years' War.",
        "He was known for his piety and founded Eton College and King’s College, Cambridge, which remain prestigious institutions today.",
        "His mental instability led to periods of incapacity, during which Richard, Duke of York, was appointed Protector of the Realm.",
        "His rule was marked by the Wars of the Roses, a series of conflicts between the rival houses of Lancaster and York, ultimately leading to his deposition and eventual death in the Tower of London.",
      ],
    },
    {
      name: "Henry V",
      gender: "m",
      src: "Henry-V.jpeg",
      reignStarted: "1413",
      hints: [
        "He is best known for a major military victory during the Hundred Years’ War, where his outnumbered forces defeated the French at the Battle of Agincourt.",
        "His reign marked a high point in English fortunes in France, culminating in a treaty that recognized him as heir to the French throne.",
        "He was admired for his leadership, discipline, and ability to inspire troops, and became a legendary figure in both history and literature.",
        "His strong rule and military success temporarily unified England under effective monarchy after a period of internal unrest.",
        "He died suddenly in France at a young age, leaving behind an infant son and an uncertain political future for both England and its claims abroad.",
      ],
    },
    {
      name: "Elizabeth I",
      gender: "f",
      src: "Elizabeth-I.jpg",
      reignStarted: "1558",
      hints: [
        "She ruled for over 44 years, in a period often referred to as a golden age of English history, marked by flourishing arts, exploration, and relative stability.",
        "Her defeat of a powerful naval invasion in 1588 established England as a major maritime power and boosted national pride.",
        "She never married, earning a lasting nickname that emphasized her independent rule and dedication to her country.",
        "Her reign saw the rise of famous cultural figures, including William Shakespeare and Christopher Marlowe, who helped shape the English Renaissance.",
        "She skillfully navigated religious tensions by establishing a moderate Protestant Church, avoiding the extremes of her predecessors’ policies.",
      ],
    },
    {
      name: "Henry VII",
      gender: "m",
      src: "Henry-VII.jpg",
      reignStarted: "1485",
      hints: [
        "He founded a new royal dynasty after defeating a rival claimant in battle, bringing an end to the Wars of the Roses.",
        "His claim to the throne was relatively weak, so he strengthened it through a strategic marriage that united two warring houses.",
        "He was known for his cautious financial policies, building up the crown’s wealth and centralizing power in the monarchy.",
        "His reign focused on restoring order, reducing the influence of over-mighty nobles, and increasing the efficiency of government.",
        "He established a lasting legacy by securing the succession for his son, whose dramatic reign would shape English history for generations.",
      ],
    },
    {
      name: "William I",
      gender: "m",
      src: "William-I.jpg",
      reignStarted: "1066",
      hints: [
        "He successfully claimed the English throne after winning the Battle of Hastings in 1066, fundamentally changing the course of English history.",
        "His reign introduced Norman culture, language, and governance structures to England, reshaping the aristocracy and legal system.",
        "He commissioned a great survey of his new kingdom, known as the Domesday Book, which recorded landholdings and resources for taxation purposes.",
        "He faced numerous rebellions and uprisings, which he suppressed with force, consolidating his control over the kingdom.",
        "His rule established a strong centralized monarchy that laid the foundations for the future English state.",
      ],
    },
  ],
};
