name: Release

on:
  pull_request:
    branches:
      - test-cicd # Only when merging into master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tag
        run: git tag v$(node -p "require('./package.json').version")-test --force && git push --tags --force
