name: Release PR

on:
  push:
    branches:
      - "github-actions"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      # - name: Create Release Commit
      #   run: npm run csversion

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Tag
        run: git tag v$(node -p "require('./package.json').version") --force && git push --tags --force
